workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Get Flutter packages
        script: |
          cd Boss
          flutter pub get
      - name: Build APK
        script: |
          cd Boss
          flutter build apk --release
    artifacts:
      - Boss/build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
          
